### ISSUE TITLE
Does not work after update - EDIT

### ISSUE THREAD

**Issue by ringnutz** [petegallagher/plugin.video.zoneminder#1]
Disregard the below, I was able to update my server (seems that it needs to be on 1.32+ for this addon to function) and then I was able to display my monitors.

HOWEVER, if there is any way you know of to fix the constant buffering that would be excellent. I can use zmninja without issue and it properly shows the live feed, but with Kodi, it plays for 1-5 seconds, then buffers for 30, then speeds up the frame rate until it catches up, then repeats indefinitely. This is not a network speed issue, as this is internal on a 1GB switch, just seems to be the stream that Kodi doesn't really like.

Apologies again, I thought this project was dead

-------------------------
ORIGINAL

I recoded the old addon a while back and had it working until this auto updated and broke it.. My bad since I thought it was a dead addon.

Anyway, I am getting 401 unauthorized when attempting to access the server now, log snippet is below

I regenerated the settings file from scratch since the format seems to have changed, and I am able to authenticate with the username and password on other devices without issue

00:21:33.772 T:140365416871104   ERROR: GetDirectory - Error getting plugin://plugin.video.zoneminder/
00:21:33.773 T:140365416871104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zoneminder/) failed
00:21:33.787 T:140364620932864  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
00:21:35.718 T:140363616835328   ERROR: 401: Unauthorized
00:21:37.903 T:140363616835328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('credentials',)
                                            Traceback (most recent call last):
                                              File "/home/aringer/.kodi/addons/plugin.video.zoneminder/zoneminder.py", line 200, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/aringer/.kodi/addons/plugin.video.zoneminder/zoneminder.py", line 172, in router
                                                _auth_token, _auth_cookies = login()
                                              File "/home/aringer/.kodi/addons/plugin.video.zoneminder/zoneminder.py", line 75, in login
                                                auth_token = j['credentials']
                                            KeyError: ('credentials',)
                                            -->End of Python script error report<--
00:21:37.967 T:140365416871104   ERROR: GetDirectory - Error getting plugin://plugin.video.zoneminder/
00:21:37.968 T:140365416871104   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zoneminder/) failed

**Comment by petegallagher** [comment]
I haven't noticed any buffering during my testing/development.

What version of Kodi are you using?
Are you using Wifi or Ethernet for your Kodi device?
Have you tried adjusting the FPS setting?

**Comment by ringnutz** [comment]
Have tried on multiple Kodi releases from Gotham to current.

Tried on raspberry pi wired ethernet as well as Ubuntu wireless laptop, same deal.

I can try the FPS setting when I get home

**Comment by ringnutz** [comment]
I tried changing the FPS to 2, and then 50. Both exhibit the same behavior, perhaps it is something with zoneminder itself?
