### ISSUE TITLE
cgibin path should be configurable

### ISSUE THREAD

**Issue by xztraz** [petegallagher/plugin.video.zoneminder#3]
kodi version: osmc 18.2
zoneminder version: v1.32.3 (on CentOS Linux release 7.6.1810 )

Tried this plugin on kodi (osmc) and i can't get it to work.  first of all zoneminer forces https and with the standard self signed cert this plugin gets an ssl error. (works fine with zmninja)

also i noticed the plugin tries to access the wrong path for newer zoneminder installations.

should be /cgi-bin-zm/ and probably some more changes of how to retreive the pictures

httpd log:
`[Mon May 20 23:50:29.906184 2019] [:error] [pid 20842] [client 192.168.1.10:58839] INF [Login successful for user "admin"]

==> /var/log/httpd/access_log <==
192.168.1.10 - - [20/May/2019:23:50:29 +0200] "POST /zm/api/host/login.json HTTP/1.1" 200 138 "-" "python-requests/2.22.0"
192.168.1.10 - - [20/May/2019:23:50:29 +0200] "HEAD /zm/cgi-bin/nph-zms?scale=auto&width=1280&height=960&mode=jpeg&maxfps=15&monitor=7& HTTP/1.1" 404 - "-" "Kodi/18.2-RC1 (X11; Linux armv7) Linux/2019.04-1 App_Bitness/32 Version/18.2-RC1"
192.168.1.10 - - [20/May/2019:23:50:29 +0200] "GET /zm/cgi-bin/nph-zms?scale=auto&width=1280&height=960&mode=jpeg&maxfps=15&monitor=7& HTTP/1.1" 404 216 "-" "Kodi/18.2-RC1 (X11; Linux armv7) Linux/2019.04-1 App_Bitness/32 Version/18.2-RC1"
192.168.1.10 - - [20/May/2019:23:50:30 +0200] "GET /zm/cgi-bin/nph-zms?scale=auto&width=1280&height=960&mode=jpeg&maxfps=15&monitor=7& HTTP/1.1" 404 216 "-" "Kodi/18.2-RC1 (X11; Linux armv7) Linux/2019.04-1 App_Bitness/32 Version/18.2-RC1"
192.168.1.200 - - [20/May/2019:23:51:12 +0200] "GET /zm/index.php?view=watch&mid=14 HTTP/1.1" 200 12798 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.84"
`

**Comment by xztraz** [comment]
i had to hardcode my zoneminder adress without the /zm/part and correct cgi. also open port 80 on zoneminder(disable redirect engine and disable reqssl). and authentication works but is veeery slow like 1-2 minutes.. så i tried without that too. now it takes maybe 10 seconds to get up a cameraview.   nice touch with the previews of the cameras but it takes a while with many cameras.

**Comment by petegallagher** [comment]
> Tried this plugin on kodi (osmc) and i can't get it to work. first of all zoneminer forces https and with the standard self signed cert this plugin gets an ssl error. (works fine with zmninja)

Your TLS certificate must be trusted by the client for this connection to work. ZMNinja must not be performing any verification of the TLS certificate for this to work.

> also i noticed the plugin tries to access the wrong path for newer zoneminder installations. should be /cgi-bin-zm/ and probably some more changes of how to retreive the pictures

I can see that there are [some entries](https://github.com/ZoneMinder/zoneminder/search?q=cgi-bin-zm&unscoped_q=cgi-bin-zm) in the codebase for `cgi-bin-zm`, but this is not the default path. I will add an option to allow this to be selected.

> i had to hardcode my zoneminder adress without the /zm/part

What do you mean by this? The default Zoneminder installs use `/zm` as their base path. If you do not have it installed at this path you can edit the `base_url` in the plugin config.

> authentication works but is veeery slow like 1-2 minutes

This has not been the case in my testing. You would need to provide a bit more information on this.

**Comment by xztraz** [comment]
i'm not sure how zmninja goes around the problem but it's user friendly ish.. :) setting upp trusted ssl certificates for a host that is only reachable within a lan that has no domainnames and such is a bit of work..

they changed default paths like a year or two ago what i can remember, when they forced over to https.

cgi-bin-zm is in root not under /zm base

i have just used the standard paths during installation and my zonminder.conf did look the same as the one on zm repo so it should be correct.

How many cameras did you have in your test setup? i have quite many streams 20+

**Comment by xztraz** [comment]
i've tried at bit more with authentication now. i think the delay is the same when i use the admin account. if using another user i have problems but that might be the user setup. so ignore the authentication slowness i wrote about. :)

but some configurable paths would be nice.

and if you have time some button to skip ssl check?

**Comment by xztraz** [comment]
this is the hardcoded bit i had to fix since cgi-bin-zm is in the root. (removed base url)
active_monitor['video'] = 'http://192.168.4.4/cgi-bin-zm/nph-zms?scale=auto&width...

from zoneminder conf
Alias /zm "/usr/share/zoneminder/www"
ScriptAlias /cgi-bin-zm "/usr/libexec/zoneminder/cgi-bin"
