### ISSUE TITLE
Zoneminder connection error with fresh install

### ISSUE THREAD

**Issue by wunderboy001** [petegallagher/plugin.video.zoneminder#7]
Hi Peter,

I installed ZM 2.0.2 on CoreELEC 9.2.5 (Kodi 18.9) and set Base URL to http://127.0.0.1:8088 (tried with LAN private IP too) no other modifications made, but I'm unable to start ZM.

I receive:
Zoneminder connection error
HTTPConnectionPool(host='127.0.0.1', port=8088): Max retries exceeded with URL: /zm/API/host/login.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xea2f48b0>: Failed to establish new connection: [Errno 111] Connection refused',))

Can you help, please? Is there any documentation to follow what modifications are required? (I'm a newbie Kodi user)

Thanks for your help in advance!

**Comment by petegallagher** [comment]
This plugin does not provide the Zoneminder service. You need to run Zoneminder somewhere within your network and connect to it from this plugin.
